# Generated by Django 5.0.1 on 2024-01-10 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('central', models.BooleanField(default=False, verbose_name='Central')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCompra', models.DateField(verbose_name='Fecha de compra')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('numFactura', models.CharField(max_length=100)),
                ('fechaFactura', models.DateField()),
                ('estado', models.CharField(choices=[('ACT', 'Activa'), ('ANU', 'Anulada')], default='ACT', max_length=3)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('prefijo', models.CharField(blank=True, max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Unidades de medida',
            },
        ),
        migrations.CreateModel(
            name='OrigenDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('almacen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.almacen')),
                ('punto_venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.puntoventa')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('cant_dis', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad disponible')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Precio de venta minoritario')),
                ('precio_venta_m', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Precio de venta mayoritario')),
                ('activo', models.BooleanField(default=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria', verbose_name='Categoría')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.unidadmedida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventario.origendestino')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventario.origendestino')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad de productos comprados')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de compra')),
                ('costo', models.FloatField(default=0)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.compra', verbose_name='Compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Compra de producto',
                'verbose_name_plural': 'Compras de productos',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad en inventario')),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('punto_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.puntoventa')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=11, unique=True, verbose_name='DNI')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('fecha_contratacion', models.DateField(verbose_name='Fecha de contratación')),
                ('tipo_lugar', models.CharField(choices=[('Almacen', 'Almacén'), ('PuntoVenta', 'Punto de Venta')], max_length=10, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empleados/', verbose_name='Imagen')),
                ('almacenes', models.ManyToManyField(to='inventario.almacen', verbose_name='Almacenes')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.puesto', verbose_name='Puesto')),
                ('punto_venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.puntoventa', verbose_name='Punto de Venta')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de productos vendidos')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de venta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
