# Generated by Django 2.2.6 on 2023-12-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='subTotal',
        ),
    ]
