# Generated by Django 2.2.6 on 2023-12-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20231225_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('ACT', 'Activa'), ('ANU', 'Anulada')], default='ACT', max_length=3),
        ),
    ]
